### ISSUE TITLE
Die Hard Trilogy (USA) crashes after booting

### ISSUE THREAD

**Issue by Kuba-J** [MiSTer-devel/Saturn_MiSTer#161]
Some users are reporting a problem with Die Hard Trilogy. It crashes after launch.  Core single and dual 20240315.

Maybe it's a sensitive case , works from my side on single ram 20240315

**Comment by Zet-sensei** [comment]
At the moment, it only works :
- with regular BIOS files, no multiregion ones;
- No RAM cartridge should be enabled on the port (otherwise the game will go on a scratchy sound loop after the FOX logo);
- the region autodetection isn't working at all on that game.

The game have 'TUK' on the disc header as compatible regions.

**Comment by Kuba-J** [comment]
No core bug , issue closed
