### ISSUE TITLE
Regression - Grandia jpn & Grandia Eng patch - texture flickering - Single RAM 

### ISSUE THREAD

**Issue by JaeOfMordor** [MiSTer-devel/Saturn_MiSTer#210]
since core revision Saturn_unstable_20240417, grandia displays a reproducible flicker to many different textured surfaces.

tested and confirmed on two different Single RAM MiSTer's, one with a 2.9 ram, one with a 3.0.

**Comment by JaeOfMordor** [comment]
https://github.com/MiSTer-devel/Saturn_MiSTer/assets/114522512/3bc88e24-45d9-404f-a641-95ff39c14037

**Comment by JaeOfMordor** [comment]
and compared with the core prior to the issue starting, 

https://github.com/MiSTer-devel/Saturn_MiSTer/assets/114522512/ffbf970c-9cdc-44c6-8a0c-d7e63c103147

Saturn_unstable_20240409

**Comment by JaeOfMordor** [comment]
the flickering can be seen from the 1st scene after the opening cutscene finishes playing,

https://github.com/MiSTer-devel/Saturn_MiSTer/assets/114522512/17d9bdc4-02b0-4aab-9ab0-34468b1793cb

Saturn_unstable_20240417 & onward

**Comment by Kuba-J** [comment]
I just wanted to add , that this flickering does not occur for every user.

**Comment by srg320** [comment]
> 73793038788__6D335A65-6618-46E5-8CF6-F1F5A022B6A4.MOV 
> this is how it appears on all cores from Saturn_unstable_20240417 & onward
> 
> the games frame-rate is also lower since this graphical issue started

How to get to that place in the game quickly?

**Comment by JaeOfMordor** [comment]
> > [73793038788](tel:73793038788)__6D335A65-6618-46E5-8CF6-F1F5A022B6A4.MOV
> > this is how it appears on all cores from Saturn_unstable_20240417 & onward
> > the games frame-rate is also lower since this graphical issue started
> 
> How to get to that place in the game quickly?

the flickering can be seen by selecting New Game and waiting for the opening cutscene to finish. 

traveling around the town also causes the town to
Stutter as the camera moves

**Comment by JaeOfMordor** [comment]
UPDATE: this looks to be an issue that can fix itself by selecting reset settings from within the core menu.

i will confirm when i get back from work in about 3 hours.

thank you for your time @srg320

**Comment by JaeOfMordor** [comment]
it is here over the bridge from the start of the game,

![image](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/114522512/daa7b930-4473-46d3-be74-6137538460eb)


you need to play until the game opens up the other half of the town

**Comment by JaeOfMordor** [comment]
the issue appears in any building you can go into
![IMG_7517](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/114522512/7551c203-2ba3-4fdc-b9ac-6e91ca2e51ce)

**Comment by JaeOfMordor** [comment]
an example 
https://github.com/MiSTer-devel/Saturn_MiSTer/assets/114522512/77cc3b49-89c6-4614-8c44-c40491e36740

**Comment by Zet-sensei** [comment]
I tried multiple times today and I can't seem to be able to reproduce that issue.

Tests were done with a 2.9 Dual RAM system, with core version 20240520.


I can leave a save game file of the translation after the 3 treasures and you need to go the to museum.
As you can wander around the town too.

[Grandia (Japan) (4M) patched.zip](https://github.com/MiSTer-devel/Saturn_MiSTer/files/15407482/Grandia.Japan.4M.patched.zip)

**Comment by L0velime** [comment]
I am also experiencing the exact same flickering in Grandia with english patch (v 1.1.1) as a CHD file using the HiSaturn v1.02 bios on the last couple of unstable core builds I have tested, which I did not experience before with previous builds. 
I have also tested with the latest unstable mister main (240520), which did not fix it.

Latest stable saturn core build seems to work as intended with no glitches in the realtime rendered opening scene though.

3.0 RAM module (seems stable at 145 MHz (60+ minutes). 5V, 4A, 20W power supply.

using
Mister v240520, OS v231108, 
Saturn unstable 240417, 240504 and 240520 all experience flickering for me.

**Comment by real-amano** [comment]
@L0velime , @JaeOfMordor  Did the reworking to Single RAM for 2.4 and 2.5 compatibility fix that issue for you or is it still reproduceable?

**Comment by L0velime** [comment]
The issue still persist, the RAM rework did not fix the issue.

**Comment by happy0wl** [comment]
I am experiencing the flickering issue in the opening realtime cutscene with the latest stable build (20240628) on my mister with single 2.9 ram. I switched back to the previous stable build (20240423) and the flickering issue is gone on my setup.

**Comment by prenetic** [comment]
Would like to add my experience here as well and include some data that might help with reproducing the issue. I'm running a Terasic DE10-Nano with the "SDRAM XS-D v2.5" memory module from Legacy Pixels (single 128 MB module, uses Alliance-branded chips), testing out at 142 MHz.

![image](https://github.com/user-attachments/assets/3efeeeda-0e08-4d77-87bd-fa00809a67a3)

![image](https://github.com/user-attachments/assets/e62ff260-2068-4ed5-b681-ab76a4451359)

This issue has consistent repro on my end with any build *after* the `Saturn_unstable_20240409_12d753` build. Aside from differences with slowdowns and the since-fixed audio rates for certain sound effects, the texture flickering problem in particular gets really bad in some areas of the game. I've enclosed a save file that you can use with the official Japanese release of the game (disc 1). Below are a couple clips demonstrating the issue in real time and where it can be triggered.

Save file:
[Grandia (Japan) (4M).zip](https://github.com/user-attachments/files/16741804/Grandia.Japan.4M.zip)

Capture from the `Saturn_unstable_20240409_12d753` build (no texture flickering):
https://github.com/user-attachments/assets/c1018a30-a8df-49de-b767-5dfdc2b8b851

Capture from the `Saturn_unstable_20240824_111077` build (has texture flickering):
https://github.com/user-attachments/assets/898df6a2-645c-4fea-a49d-9189e8ffa65e

**Comment by prenetic** [comment]
Would like to add my experience here as well and include some data that might help with reproducing the issue. I'm running a Terasic DE10-Nano with the "SDRAM XS-D v2.5" memory module from Legacy Pixels (single 128 MB module, uses Alliance-branded chips), testing out at 142 MHz.

![image](https://github.com/user-attachments/assets/3efeeeda-0e08-4d77-87bd-fa00809a67a3)

![image](https://github.com/user-attachments/assets/e62ff260-2068-4ed5-b681-ab76a4451359)

This issue has consistent repro on my end with recent builds, and no repro with the `Saturn_unstable_20240409_12d753` build. I chose to test this build based on other user's reports, but am not certain this is when the issue was introduced.

Aside from differences with slowdowns and the since-fixed audio rates for certain sound effects, the texture flickering problem in particular gets really bad in some areas of the game. As others have indicated, resetting/deleting the Saturn core's settings has had no impact.

I've enclosed a save file that you can use with the official Japanese release of the game (disc 1). Below are a couple clips demonstrating the issue in real time and where it can be triggered.

Save file:
[Grandia (Japan) (4M).zip](https://github.com/user-attachments/files/16741804/Grandia.Japan.4M.zip)

Capture from the `Saturn_unstable_20240409_12d753` build (no texture flickering):
<video src="https://github.com/user-attachments/assets/c1018a30-a8df-49de-b767-5dfdc2b8b851" />

Capture from the `Saturn_unstable_20240824_111077` build (has texture flickering):
<video src="https://github.com/user-attachments/assets/898df6a2-645c-4fea-a49d-9189e8ffa65e" />

**Comment by srg320** [comment]
> This issue has consistent repro on my end with recent builds, and no repro with the `Saturn_unstable_20240409_12d753` build. I chose to test this build based on other user's reports, but am not certain this is when the issue was introduced.
> 
> Aside from differences with slowdowns and the since-fixed audio rates for certain sound effects, the texture flickering problem in particular gets really bad in some areas of the game. As others have indicated, resetting/deleting the Saturn core's settings has had no impact.
> 
> I've enclosed a save file that you can use with the official Japanese release of the game (disc 1). Below are a couple clips demonstrating the issue in real time and where it can be triggered.

I have tested on this save and on different builds. Unfortunately I can't reproduce this issue. And I have no idea how to do it.

**Comment by happy0wl** [comment]
I have tested the save file on the 240824 build on mister and I get the same texture flickering in that particular room. I can trigger the flickers just by walking around the room.

https://github.com/user-attachments/assets/e2200ff8-d62a-42b7-a6b3-a037eb718ef8

**Comment by Kuba-J** [comment]
I have tested 4 micro sd cards , on two of the same brand Sandisk  I have flickering already during the intro on the ship , with the card kioxioa and samsung , the flickering does not occur.

**Comment by L0velime** [comment]
I got the same type of samsung card as Kuba-J above, except mine 512gb and does flicker. This issue is so weird.

@srg320 even if you have no way to reproduce the flickering issues, have you seen the other obove mentioned issue, where the floors and objects desync in movement?, 
if you have any idea why that is happening, maybe solving that might fix the flickering?

**Comment by srg320** [comment]
> @srg320 even if you have no way to reproduce the flickering issues, have you seen the other obove mentioned issue, where the floors and objects desync in movement?,
> if you have any idea why that is happening, maybe solving that might fix the flickering?

The ground is drawn by the VDP2 (Rotation scroll screen 0). Everything on the ground is drawn by the VDP1. It seems that coordinates of each video processor are sometimes updated in different frames. Perhaps this is normal game behavior.
Only polygons drawn by the VDP1 are flickering. But these two problems are not related.

**Comment by JaeOfMordor** [comment]
the flickering is gone as of the latest dual-ram build. only remains on single ram

**Comment by prenetic** [comment]
@JaeOfMordor can you please reopen this? Multiple people with single RAM builds are still experiencing the issue, it is not resolved/completed.

**Comment by JaeOfMordor** [comment]
@prenetic reopening the issue - as is - would be the wrong call.

it was a completely unpredictable, edge case phenomenon that could be caused by anything, sdram, sdcard, the particular de10/alternative or maybe it was caused by how all the components in your specific setup interacted between themselves.

the ram timings, now split between two sdram modules, has finally lead to a consistent fix as the core dev intended.

**Comment by zakk4223** [comment]
On single ram I discovered today if I turn on Fast Timing AND overclock the ram to 950Mhz the flickering is entirely gone.

I also found if I UNDERCLOCK the ram to around 725Mhz it flickers badly. So doing that might be help to reproduce and at least see what the game is doing when stuff flickers

**Comment by jhdgghost** [comment]
Only confirm that i have the same issue with my new mister pi setup. Flicker clearly and the intro flickers exactly as is shown in 73793200542__6A518E90-0DDD-4BB5-A4C1-8FA7AC1A559D.MOV from JaeOfMordor the SD card is the one is provided in the turbo Mister pi setup.
