### ISSUE TITLE
Croc - Legend of the Gobbos (USA) // Freezes during the second part of the introduction

### ISSUE THREAD

**Issue by Zet-sensei** [MiSTer-devel/Saturn_MiSTer#69]
When the bad guy (Baron Dante) appears on the intro for kidnapping the Gobbos, the game freezes with only some sounds continuing.

**Comment by InfernoHabanero** [comment]
I want to add that it might depend on the build or it might just be a case of it _sometimes_ freezing, since I tested out the cutscene and it didn't crash for me.

I'm assuming there is something related to how the core is rendering Baron Dante and his minions that it doesn't like, since from my experience that is when the introduction begins to implode on itself.

**Comment by Zet-sensei** [comment]
Fixed with commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/441401f792624fe72c2aa97fa3db2aa3213e6c61
